//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBookStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int PKBookId { get; set; }
        public string BookName { get; set; }
        public string BookDescription { get; set; }
        public string BookImageURL { get; set; }
        public string AuthorName { get; set; }
        public decimal Price { get; set; }
        public decimal OfferedPrice { get; set; }
        public int Rating { get; set; }
        public int FKAddedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
